// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgqo_vRppRPp9ZEjcM4OkNSWdyDOWdTQ',
    appId: '1:325042115318:web:a7aea04e88472813f2d2d7',
    messagingSenderId: '325042115318',
    projectId: 'racevision-tud',
    authDomain: 'racevision-tud.firebaseapp.com',
    storageBucket: 'racevision-tud.firebasestorage.app',
    measurementId: 'G-D623N10LJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA9grj2Zl47zDqkrXyBq9SG2Gq-04qkCA',
    appId: '1:325042115318:android:2b9bd9147995c931f2d2d7',
    messagingSenderId: '325042115318',
    projectId: 'racevision-tud',
    storageBucket: 'racevision-tud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkm9aRrLdD5a0T5qkbUdbRMr2_xPt_Vkc',
    appId: '1:325042115318:ios:66e53c15328b5ebbf2d2d7',
    messagingSenderId: '325042115318',
    projectId: 'racevision-tud',
    storageBucket: 'racevision-tud.firebasestorage.app',
    iosBundleId: 'com.example.racevision',
  );
}
